# -*- coding: utf-8 -*-
"""NLPtext.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oc4lOTvEFPsVGmWkyW02c5Jm-UU5Hy4i
"""

!pip install transformers

"""# Text Classifier::"""

from transformers import pipeline
access_token = your_access_token
classifier = pipeline("sentiment-analysis", model='distilbert-base-uncased-finetuned-sst-2-english')
result = classifier("This is by far the best product I have ever used; it exceeded all my expectations.")
print(result)

classifier(["This design of your new website is likeable",
            "The new website is so awful"])

classifier = pipeline("zero-shot-classification")
classifier(
    "Photosynthesis is the process by which green plants use sunlight to synthesize nutrients from carbon dioxide and water.",
    candidate_labels=["education", "science", "business"],
)

classifier(
    "MNCs should want to expand in other countries.",
    candidate_labels=["education", "science", "business"],
)

"""# Text Generator:"""

generator = pipeline("text-generation", model="distilgpt2")
generator(
"i love  her but can't able to say",
max_length=1000, num_return_sequences=2,
)

"""# Text Summarizer"""

summarizer = pipeline("summarization")
text = """
San Francisco, officially the City and County of San Francisco, is a commercial and cultural center in the northern region of the U.S. state of California. San Francisco is the fourth most populous city in California and the 17th most populous in the United States, with 808,437 residents as of 2022.
"""
summary = summarizer(text, max_length=50, min_length=25, do_sample=False)
print(summary)

"""# Text Translator"""

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")
translation = translator("L'engagement de l'entreprise envers l'innovation et l'excellence est véritablement inspirant.")
print(translation)

